# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bf62b2a4dbe077350e1afa47955bea8c0a17b684e1f1c2f7bc7de2f339a493ac497fb30c051ec5988d6573781d7e89bcda68597ffc19fe2f5712204fe05b734

test:
  secret_key_base: 6736327481f64453a8e17134910b5e624eee0091c83394908e702219b0fc3a88759aa6f9ae4372aca28374cdefdfe575e83623935583163d243f8e958350ff95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
